spring:
  application:
    name: tada

  config:
    import: optional:file:.env.local[.properties]

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
    username: postgres.ylwozrffjxrfqebjwbfo
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

jwt:
  # JWT 서명에 사용할 비밀키
  # 실제 값은 .env.local의 JWT_SECRET에서 가져온다.
  secret: ${JWT_SECRET}

  # JWT 유효시간
  # 3600000 = 1시간
  expiration: 3600000